### ISSUE TITLE
what's the difference between yours and "4D Gaussian Splatting for Real-Time Dynamic Scene Rendering"

### ISSUE THREAD

**Issue by lcc815** [nnanhuang/S3Gaussian#11]
I think these two are so similar that I can't distinguish what difference they have between them

**Comment by FudongGe** [comment]
I have the same confusion.

**Comment by Treeeplanter** [comment]
Same confusion. This seems to be just a porting of the "4D Gaussian" concept to the streetscape realm.

**Comment by nnanhuang** [comment]
Thanks for the discussion! The main objective of our paper is to build a 4D Gaussian model for autonomous driving scenarios without the use of bounding box supervision. 4DGsussians is a good framework for combining hexplanes with 3D Gaussians, but it cannot be directly used for large-scale and highly dynamic autonomous driving scenarios. To address this challenge, we employ a clip-based modeling strategy to efficiently adapt 3DGS for large-scale scenes. We initialize Gaussians using LiDAR point clouds to achieve better geometry and provide corresponding depth supervision. We also make several driving-specific adaptations like consideration of rigid motions (e.g., cars), semantic information (e.g., buildings), and temporal color changes (e.g., traffic signals).  To achieve self-supervised static/dynamic disentanglement, we introduce a regularization term to the spatial-temporal field considering the characteristics of driving scenarios.

**Comment by dachengxiaocheng** [comment]
I have the same concern!

**Comment by chenj02** [comment]
I don't find there‘s any different......
